add test for endpoint that sleeps
cloudfoundry/cf-networking-release pull request #235
Opened 2023-08-15 00:03 UTC by reneighbor

add test for endpoint that sleeps before responding 200, to test readines invocation timeout

2023-08-15 00:17 UTC, jrussett requested changes
Can you please update [proxy's README](https://github.com/cloudfoundry/cf-networking-release/blob/develop/src/example-apps/proxy/README.md) to document the new `/sleepy/` endpoint.

2023-08-15 12:59 UTC, ameowlia approved these changes, later dismissed

2023-09-29 19:39 UTC, MarcPaquette commented
> Can you please update [proxy's README](https://github.com/cloudfoundry/cf-networking-release/blob/develop/src/example-apps/proxy/README.md) to document the new `/sleepy/` endpoint?

@jrussett I updated the readme for this. Okay to merge?

2023-10-03 19:53 UTC, jrussett approved these changes

2023-10-10 20:35 UTC, merged